# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:      # pipeline-level
  projName: 'helium-java'
  topicName: '$(Build.SourceBranchName)'
  appName: 'java'

stages:
- stage: Build_Container
  displayName: Build the App and publish it in Azure Container Registry
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: AzureCLI@1
      inputs:
        azureSubscription: 'az sub'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr login --name $(appName)heliumacr \
          docker build --target=release -t $(appName)heliumacr.azurecr.io/helium:canary . \
          docker push $(appName)heliumacr.azurecr.io/helium:canary'

# - stage: Code_Analysis
#   displayName: Check Code Quality with Sonar
#   dependsOn: Build_Container
#   condition: succeeded() 
#   jobs:
#   - job: CodeAnalysis
    
#     pool:
#       vmImage: 'ubuntu-latest'

#     steps:
#     - task: Bash@3
#       inputs:
#         targetType: 'inline'
#         script: 'echo test 2'

# - stage: Integration_Tests
#   displayName: Run Integration Tests with the new App in Azure
#   dependsOn: Code_Analysis
#   condition: succeeded() 
#   jobs:
#   - job: Integrationtest
#     pool:
#       vmImage: 'ubuntu-latest'

#     steps:
#     - task: Bash@3
#       inputs:
#         targetType: 'inline'
#         script: 'echo test 3'
